name: rbp-maps
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - bedtools>=2.31
  - matplotlib>=3.10
  - numpy>=2.2
  - pandas>=2.2
  - pip
  - pybedtools>=0.12
  - pybigwig>=0.3.25
  - pysam>=0.23.3
  - pytest>=8.3
  - samtools>=1.22
  - scipy>=1.17
  - seaborn>=0.13.2
  - setuptools>=75
  - tqdm>=4.67
  - ucsc-bedgraphtobigwig
  - ucsc-bedtobigbed
